# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: tmaier/docker-compose:latest

services:
  - docker:dind
before_script:
  - docker info
  - docker-compose --version
  
build:
  stage: build
  script:
    docker-compose up --build -d
    curl localhost | grep 'html'