
version: '2'

volumes:
  buildstatic:
    driver: local

services:
  application:
    build: ./efDev
    container_name:
      application
    environment:
      DB_HOST: store
      VIRTUAL_HOST: application
    depends_on:
      [wait, imagemagick, front-end]
    volumes: 
      - buildstatic:/usr/src/app/build
      - ~/www/back-end:/usr/src/app
  store:
    image: mongo
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: application
  wait: 
    image: dadarek/wait-for-dependencies
    command:
       store:27017
    links:
      - store
      - imagemagick
  imagemagick:
   image:  acleancoder/imagemagick-full
  front-end:
    build: ./front-end/
    volumes:
      - buildstatic:/usr/src/build
      - ~/www/build:/usr/src/build