
version: '2'

volumes:
  buildstatic:
    driver: local

services:
  application:
    build: .
    container_name:
      application
    environment:
      DB: "efsite"
      DB_USER: 'admin'
      DB_PASS: "metallic"
      VIRTUAL_HOST: application
    depends_on:
      [wait, imagemagick, front-end]
    volumes: 
      - buildstatic:/usr/src/app/build
      - /Users/ilya/Desktop/storage:/usr/src/app/storage
  store:
    image: tutum/mongodb
    environment:
      MONGODB_USER: "admin"
      MONGODB_PASS: "metallic"
      MONGODB_DATABASE: "efsite"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: application
  wait: 
    image: dadarek/wait-for-dependencies
    command:
       store:27017
    links:
      - store
      - imagemagick
  imagemagick:
   image:  acleancoder/imagemagick-full
  front-end:
    build: ../front-end
    volumes:
      - buildstatic:/usr/src/build