
version: '2'

services:
  application:
    image: ilyazubkov/mgsu_site
    container_name:
      application
    ports:
      - 4000:4000
    environment:
      DB: "efsite"
      DB_USER: 'admin'
      DB_PASS: "metallic"
      VIRTUAL_HOST: application
  store:
    image: tutum/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "admin"
      MONGODB_PASS: "metallic"
      MONGODB_DATABASE: "efsite"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: application
  wait: 
    image: dadarek/wait-for-dependencies
    command:
       store:27017
    links:
      - store
      - imagemagick
  imagemagick:
   image:  acleancoder/imagemagick-full